/**
 * Planet Builder — Pico-8 Export Pipeline
 * Converts a planet JSON → .p8 cartridge (Lua)
 */

const TILE_COLOR={0:0,1:11,2:3,3:4,4:1,5:5,6:6,7:7,8:10,9:8};

export function exportToPico8(planet) {
  return ['pico-8 cartridge // http://www.pico-8.com','version 41','__lua__',buildLua(planet),'__map__',buildMapData(planet),'__gfx__',buildSpriteData(),'__sfx__','','__music__','','<!-- end of file -->'].join('\n');
}

function buildLua(planet) {
  const creatures=planet.creatures.slice(0,8).map(c=>`  {id="${c.id}",name="${c.name}",hp=${c.stats?.hp||30},atk=${c.stats?.attack||15},def=${c.stats?.defense||10},spd=${c.stats?.speed||12}}`).join(',\n');
  return `-- ${planet.name}\n-- seed: ${planet.seed||'custom'}\n-- generated by planet builder\nlocal px,py=64,64\nlocal in_battle=false\nlocal battle_enemy=nil\nlocal battle_turn="player"\nlocal msg=""\nlocal msg_timer=0\nlocal creatures={\n${creatures}\n}\nfunction _init() px,py=64,64 music(0) end\nfunction _update()\n  if in_battle then update_battle()\n  else update_overworld() end\n  if msg_timer>0 then msg_timer-=1 end\nend\nfunction update_overworld()\n  local dx,dy=0,0\n  if btn(0) then dx=-1 end if btn(1) then dx=1 end\n  if btn(2) then dy=-1 end if btn(3) then dy=1 end\n  local nx,ny=px+dx,py+dy\n  local t=mget(nx,ny)\n  if t~=4 and t~=5 and t~=9 then px,py=nx,ny end\n  if (dx~=0 or dy~=0) and rnd(1)<0.08 then start_battle() end\nend\nfunction start_battle()\n  in_battle=true\n  local idx=flr(rnd(#creatures))+1\n  battle_enemy={name=creatures[idx].name,hp=creatures[idx].hp,max_hp=creatures[idx].hp,atk=creatures[idx].atk,def=creatures[idx].def}\n  msg="a wild "..battle_enemy.name.." appeared!" msg_timer=90 battle_turn="player"\nend\nfunction update_battle()\n  if battle_turn=="player" then\n    if btnp(4) then\n      local dmg=max(1,15-battle_enemy.def) battle_enemy.hp-=dmg\n      msg="you deal "..dmg.." dmg!" msg_timer=60\n      if battle_enemy.hp<=0 then msg=battle_enemy.name.." fainted!" msg_timer=90 in_battle=false\n      else battle_turn="enemy" end\n    elseif btnp(5) then msg="got away!" msg_timer=60 in_battle=false end\n  elseif battle_turn=="enemy" then\n    if msg_timer<=0 then\n      local dmg=max(1,battle_enemy.atk-10)\n      msg=battle_enemy.name.." hits for "..dmg.."!" msg_timer=60 battle_turn="player"\n    end\n  end\nend\nfunction _draw()\n  cls(0)\n  if in_battle then draw_battle() else draw_overworld() end\n  if msg_timer>0 then rectfill(0,96,128,128,1) print(msg,4,100,7) end\nend\nfunction draw_overworld()\n  map(0,0,0,0,16,16)\n  rectfill(px*8-4,py*8-4,px*8+4,py*8+4,11)\nend\nfunction draw_battle()\n  rectfill(0,0,128,128,1)\n  print(battle_enemy.name,40,20,7)\n  local pct=battle_enemy.hp/battle_enemy.max_hp\n  rectfill(30,30,98,34,5) rectfill(30,30,30+flr(68*pct),34,11)\n  rectfill(0,96,128,128,2) print("z:attack  x:run",10,104,7)\nend\n`;
}

function buildMapData(planet) {
  const grid=Array.from({length:16},()=>Array(16).fill(0));
  let bx=0;
  for(const biome of planet.biomes) {
    const tiles=biome.tiles||[];
    const bh=Math.min(tiles.length,16),bw=Math.min((tiles[0]||[]).length,16-bx);
    for(let y=0;y<bh;y++) for(let x=0;x<bw;x++) grid[y][bx+x]=tiles[y]?.[x]??0;
    bx+=bw; if(bx>=16) break;
  }
  return grid.map(row=>row.map(t=>(TILE_COLOR[t]||0).toString(16)).join('')).join('\n');
}

function buildSpriteData(){return Array(32).fill('0'.repeat(64)).join('\n');}
